const images = {
    logo: require('./logo.svg').default,
    HeaderBG: require('./HeaderBg.svg').default,
    HeroImg: require('./hero img.png'),
    HeroBG: require('./heroBg.svg').default,
    CircleArrow: require('./CircleArrow.svg').default,
    shape1: require('./shape1.svg').default,
    logoSymbol: require('./logoSymbol.svg').default,
    rightHover: require('./right-hover.svg').default,
    leftNormal: require('./left-normal.svg').default,
    whoweareIMG: require('./whoweareIMG.png'),
    leftNormal1: require('./left-normal(1).svg').default,
    ServicesIcon1: require('./ServicesIcon1.svg').default,
    ServicesIcon2: require('./ServicesIcon2.svg').default,
    ServicesIcon3: require('./ServicesIcon3.svg').default,
    ServicesIcon4: require('./ServicesIcon4.svg').default,
    Phone: require('./phone.png'),
    FeatureWork: require('./featureWorksIMG.svg').default,
    PortFolio1: require('./PortFolio1.png'),
    PortFolio2: require('./PortFolio2.png'),
    PortFolio3: require('./PortFolio3.png'),
    PortFolio4: require('./PortFolio4.png'),
    PhoneIllustration: require('./phoneillustration.png'),
    SpeachBubble: require('./SpeachBubble.svg').default,
    FbIcon: require('./Fb.svg').default,
    YtbIcon: require('./Ytb.svg').default,
    InstaIcon: require('./Insta.svg').default,
    viewButton: require('./viewButton.svg').default,
    burgerIcon: require('./burgerIcon.svg').default,
    PathStroke: require('./Path(Stroke).svg').default,
};

export default images;